### ISSUE TITLE
cmake compilation error

### ISSUE THREAD

**Issue by parlange** [MRASL/mrasl_guidance_ros#6]
Hi, I am trying to split GuidanceNode so that it publishes topics for all 5 cameras at the same time.
I found this modified version, but I am getting a compilation error: 

`CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "mrasl" with any of
  the following names:

    mraslConfig.cmake
    mrasl-config.cmake

  Add the installation prefix of "mrasl" to CMAKE_PREFIX_PATH or set
  "mrasl_DIR" to a directory containing one of the above files.  If "mrasl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  mrasl_guidance_ros/CMakeLists.txt:16 (find_package)

-- Could not find the required component 'mrasl'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "mrasl" with any of
  the following names:

    mraslConfig.cmake
    mrasl-config.cmake

  Add the installation prefix of "mrasl" to CMAKE_PREFIX_PATH or set
  "mrasl_DIR" to a directory containing one of the above files.  If "mrasl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  mrasl_guidance_ros/CMakeLists.txt:16 (find_package)

-- Configuring incomplete, errors occurred!
`
How can I run the modified node? Thank you.

**Comment by andre-nguyen** [comment]
Oh sorry about that, I never got around to removing references to our internal MRASL library but basically all code relating to MissionPlannerRequest and such can be safely removed. It used to be a way for us to remotely kill nodes from a state machine.

**Comment by andre-nguyen** [comment]
Looks like I can't trivially fix it. This package was developped with ROS indigo (the manifold had indigo installed on it) and my desktop is currently on Kinectic, this is creating some opencv conflicts on my side.

You're welcome to send in a pull request. If you're on indigo, just remove a few lines in guidance_node.cpp.

**Comment by andre-nguyen** [comment]
OK I got a fix in. If you're on opencv 2.4 (e.g. ROS indigo) try the master branch, if you're on Kinetic try out the bug/kinetic branch.

In any case, I'm not sure you have enough bandwidth on the USB port to receive 5 images at the same time. You might have to experiment with reducing the rate or something. The DJI Guidance configuration utility is good for this as there's a meter in it telling you how much bandwidth you have left when selecting the data streams you want to receive.

**Comment by parlange** [comment]
Hi, I cloned the master branch as I am working with ROS Indigo.
When I compile the catkin using catkin_make I get:

`Base path: /home/parlange/guidance_mod_ws
Source space: /home/parlange/guidance_mod_ws/src
Build space: /home/parlange/guidance_mod_ws/build
Devel space: /home/parlange/guidance_mod_ws/devel
Install space: /home/parlange/guidance_mod_ws/install
####
#### Running command: "cmake /home/parlange/guidance_mod_ws/src -DCATKIN_DEVEL_PREFIX=/home/parlange/guidance_mod_ws/devel -DCMAKE_INSTALL_PREFIX=/home/parlange/guidance_mod_ws/install -G Unix Makefiles" in "/home/parlange/guidance_mod_ws/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/parlange/guidance_mod_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/parlange/guidance_mod_ws/devel;/home/parlange/guidance_ws/devel;/home/parlange/tum_simulator_ws/devel;/opt/ros/indigo
-- This workspace overlays: /home/parlange/guidance_mod_ws/devel;/home/parlange/guidance_ws/devel;/home/parlange/tum_simulator_ws/devel;/opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/parlange/guidance_mod_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - mrasl_guidance
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'mrasl_guidance'
-- ==> add_subdirectory(mrasl_guidance_ros)
-- Using these message generators: gencpp;genlisp;genpy
CMake Warning at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "mrasl" with any of
  the following names:

    mraslConfig.cmake
    mrasl-config.cmake

  Add the installation prefix of "mrasl" to CMAKE_PREFIX_PATH or set
  "mrasl_DIR" to a directory containing one of the above files.  If "mrasl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  mrasl_guidance_ros/CMakeLists.txt:16 (find_package)


-- Could not find the required component 'mrasl'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "mrasl" with any of
  the following names:

    mraslConfig.cmake
    mrasl-config.cmake

  Add the installation prefix of "mrasl" to CMAKE_PREFIX_PATH or set
  "mrasl_DIR" to a directory containing one of the above files.  If "mrasl"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  mrasl_guidance_ros/CMakeLists.txt:16 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/parlange/guidance_mod_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/parlange/guidance_mod_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
`
After that I try to roslaunch the guidanceNode.cpp and i get:

`ERROR: cannot launch node of type [mrasl_guidance/guidance]: can't locate node [guidance] in package [mrasl_guidance]`

Am I doing something wrong? Thanks for the support.

**Comment by andre-nguyen** [comment]
Did you clean your workspace and pull the latest commit 814d969 ? Because there are no more references to package `mrasl` in `CMakeLists.txt` so it looks like you're not compiling the right thing.

Also I usually use [catkin tools](https://catkin-tools.readthedocs.io/en/latest/) instead of the old `catkin_make`. Not sure if this changes anything.

**Comment by parlange** [comment]
Sorry for the late reply. I cleaned my workspace, pulled that commit and compiled successfully using catkin_tools. Great work and thank you for the support! @andre-nguyen

**Comment by andre-nguyen** [comment]
Great, let us know if there is anything else.
